Release phase02 part2
Star-Academy/Summer1403-SE-Team05 pull request #4
Opened 2024-07-23 08:42 UTC by amiralirahimii

2024-07-23 11:50 UTC, AliSK81 requested changes, later dismissed

2024-07-23 11:50 UTC, AliSK81 commented on Phase02/Phase02-FullTextSearch/Services/FileReader.cs
> +            }
linq

2024-07-23 11:50 UTC, AliSK81 commented on Phase02/Phase02-FullTextSearch/Services/InvertedIndex.cs
> +            _invertedIndex[token].Add(fileName);
linq

2024-07-23 11:50 UTC, AliSK81 commented on Phase02/Phase02-FullTextSearch/Services/InvertedIndex.cs
> +        else
```suggestion
```

2024-07-23 14:58 UTC, amiralirahimii commented on Phase02/Phase02-FullTextSearch/Services/FileReader.cs
> +            }
solved.

2024-07-23 15:01 UTC, amiralirahimii commented on Phase02/Phase02-FullTextSearch/Services/InvertedIndex.cs
> +            _invertedIndex[token].Add(fileName);
solved.

2024-07-23 15:03 UTC, amiralirahimii commented on Phase02/Phase02-FullTextSearch/Services/InvertedIndex.cs
> +        else
بله از لحاظ منطقی حرفتون درسته و به نظرم این نکته یه نکته ی سلیقه ای هستش. از نظر من گذاشتن اون else به خواننده کد کمک میکنه که بدونه کد یا تو If میره یا تو else متناظر، درسته که با اون return هم میشه به نتیجه متناظر رسید اما کمی دقت بیشتر میخواد که من ترجیح میدم اون رو صریح نشون بدم. ضمن اینکه به نظرم زیباتر هم هست.

2024-07-24 13:55 UTC, HamedSY commented on Phase02/Phase02-FullTextSearch/UI/UserInterface.cs
> +    private (List<string>, List<string>, List<string>) ParseCommand(string command)
چرا به جای tuple برای این سه تا لیست یه کلاس نساختید؟ به نظرم تمیزتر و بهتره

2024-07-24 13:55 UTC, HamedSY commented on Phase02/Phase02-FullTextSearch/UI/UserInterface.cs
> +        List<string> notWords = new List<string>();
این اسما خیلی مفهوم لیستا رو نشون نمیده به نظرم... صرفا یه ویژگی ازشون میگه که مثلا قراره and بشن یا or یا not. اسم واقعا باید نشون بده اون متغیر چیو توش نگه داشته

2024-07-24 13:55 UTC, HamedSY commented on Phase02/Phase02-FullTextSearch/UI/UserInterface.cs
> +        List<string> notWords = new List<string>();
وقتی new List کردی دیگه var استفاده کن

2024-07-24 14:15 UTC, amiralirahimii commented on Phase02/Phase02-FullTextSearch/UI/UserInterface.cs
> +    private (List<string>, List<string>, List<string>) ParseCommand(string command)
solved.

2024-07-24 14:15 UTC, amiralirahimii commented on Phase02/Phase02-FullTextSearch/UI/UserInterface.cs
> +        List<string> notWords = new List<string>();
solved.

2024-07-24 14:38 UTC, HamedSY approved these changes

2024-07-24 14:39 UTC, merged